# SETUP PARA API DE DESENVOLVIMENTO DA DITECI
version: '1.0'
services:
    postgres:
        image: postgres
        volumes:
            - '.:/api'
        ports:
            - "2029:5432"
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        networks:
            - api-net
    api:
        build: ./api
        container_name: api-dev
        volumes:
            - ./api:/app
        environment:
            - DB_SERVER=dev-postgres
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        ports:
            - "8080:8080"
        depends_on:
            - postgres
        networks:
            - api-net

# TODO: MELHORAR OS PONTOS DE VOLUME E NETWORK
networks:
    api-net:
        driver: bridge
